### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by kenrick95** [Stellarium/stellarium-web#4]
After I run `yarn` and `yarn run dev`, I encountered this error:

```
yarn run v1.7.0
$ webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
 10% building modules 5/6 modules 1 active ...rc\assets\js\stellarium-web-engine.js[BABEL] Note: The code generator has deoptimised the styling of "PATH/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".                                   14% building modules 40/66 modules 26 active ...ng\components\observation-details.vue[BABEL] Note: The code generator has deoptimised the styling of "PATH/node_modules/vuetify/dist/vuetify.js" as it exceeds the 24% building modules 122/127 modules 5 active ...ium-web\node_modules\lodash\lodash.js[BABEL] Note: The code generator has deoptimised the styling of "PATH/node_modules/lodash/lodash.js" as it exceeds the max of  95% emitting

 ERROR  Failed to compile with 1 errors                                                                         21:24:14

PATH\build\utils.js:94
    const filename = error.file.split('!').pop()
                                ^

TypeError: Cannot read property 'split' of undefined
    at FriendlyErrorsWebpackPlugin.onErrors (PATH\build\utils.js:94:33)
    at FriendlyErrorsWebpackPlugin.displayErrors (PATH\node_modules\friendly-errors-webpack-plugin\src\friendly-errors-plugin.js:107:12)
    at Compiler.doneFn (PATH\node_modules\friendly-errors-webpack-plugin\src\friendly-errors-plugin.js:51:14)
    at Compiler.applyPlugins (PATH\node_modules\tapable\lib\Tapable.js:61:14)
    at Watching._done (PATH\node_modules\webpack\lib\Compiler.js:105:17)
    at compiler.emitRecords.err (PATH\node_modules\webpack\lib\Compiler.js:79:19)
    at Compiler.emitRecords (PATH\node_modules\webpack\lib\Compiler.js:371:38)
    at compiler.emitAssets.err (PATH\node_modules\webpack\lib\Compiler.js:62:20)
    at applyPluginsAsyncSeries1.err (PATH\node_modules\webpack\lib\Compiler.js:364:12)
    at next (PATH\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (PATH\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (PATH\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (PATH\node_modules\webpack\lib\Compiler.js:361:9)
    at require.forEach.err (PATH\node_modules\webpack\lib\Compiler.js:350:15)
    at PATH\node_modules\async\dist\async.js:473:16
    at iteratorCallback (PATH\node_modules\async\dist\async.js:1064:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Environment:

- Windows 10 (Version 10.0.17134.228)
- NPM 5.6.0
- Yarn 1.7.0
- Node v8.11.3

**Comment by xalioth** [comment]
Hi,

I never tried to build on windows. The best would be that you install docker and make, and use the provided Docker files for building. It will ensure that you have a consistent dev environement.

use "make setup" and "make dev" to setup the build env, and build/serve the page

**Comment by kenrick95** [comment]
Hi,

Yeah, it seems like build issue on Windows. I tried building on Bash on Windows 🙈 and it works well.

Thanks for the support :)
